### PR TITLE
update nom to 2.0

### PR DESCRIPTION
**Pull request by yanns**
https://unhandledexpression.com/2016/11/25/this-year-in-nom-2-0-is-here/

### CODE REVIEW

**Comment by hjr3** [comment]
I have some of the `chain!` calls converted to `do_parse!` in another branch too.

**Comment by yanns** [comment]
Oh I oversaw this deprecation.
Rust does not warn about this. (Maybe it is not possible yet.)

**Comment by hjr3** [comment]
No worries. I did it mainly to make sure I understood the new format.

**Comment by yanns** [comment]
I was just expected rustc to emits warning when compiling with deprecated functions.

**Pull request merged**
