### PR TITLE
Refactor to use revamped tokio-proto

### LINKED ISSUE #35: handle response body when the head is sent before the body
When getting an asset directly on the server (port 9000)
```
wget http://localhost:9000/assets/javascripts/jquery-1.7.1.min.js
--2016-11-29 10:39:19--  http://localhost:9000/assets/javascripts/jquery-1.7.1.min.js
Resolving localhost... ::1, 127.0.0.1
Connecting to localhost|::1|:9000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 93868 (92K) [application/javascript]
Saving to: ‘jquery-1.7.1.min.js’

jquery-1.7.1.min.js                                                 100%[===================================================================================================================================================================>]  91.67K  --.-KB/s    in 0s

2016-11-29 10:39:19 (220 MB/s) - ‘jquery-1.7.1.min.js’ saved [93868/93868]
```
```
12	18.907855	::1	::1	TCP	88	57009→9000 [SYN] Seq=0 Win=65535 Len=0 MSS=16324 WS=32 TSval=227255021 TSecr=0 SACK_PERM=1
13	18.907918	::1	::1	TCP	88	9000→57009 [SYN, ACK] Seq=0 Ack=1 Win=65535 Len=0 MSS=16324 WS=32 TSval=227255021 TSecr=227255021 SACK_PERM=1
14	18.907928	::1	::1	TCP	76	57009→9000 [ACK] Seq=1 Ack=1 Win=407776 Len=0 TSval=227255021 TSecr=227255021
15	18.907938	::1	::1	TCP	76	[TCP Window Update] 9000→57009 [ACK] Seq=1 Ack=1 Win=407776 Len=0 TSval=227255021 TSecr=227255021
16	18.907960	::1	::1	HTTP	256	GET /assets/javascripts/jquery-1.7.1.min.js HTTP/1.1 

GET /assets/javascripts/jquery-1.7.1.min.js HTTP/1.1
User-Agent: Wget/1.18 (darwin15.5.0)
Accept: */*
Accept-Encoding: identity
Host: localhost:9000
Connection: Keep-Alive

17	18.907986	::1	::1	TCP	76	9000→57009 [ACK] Seq=1 Ack=181 Win=407616 Len=0 TSval=227255021 TSecr=227255021
18	18.914313	::1	::1	TCP	329	[TCP segment of a reassembled PDU]

HTTP/1.1 200 OK
ETag: "efab29516dc38c40118a01a7888ffd6b30e8b971"
Cache-Control: no-cache
Last-Modified: Tue, 08 Mar 2016 10:25:02 GMT
Content-Length: 93868
Content-Type: application/javascript; charset=utf-8
Date: Tue, 29 Nov 2016 09:39:19 GMT

19	18.914349	::1	::1	TCP	76	57009→9000 [ACK] Seq=181 Ack=254 Win=407520 Len=0 TSval=227255027 TSecr=227255027
20	18.916082	::1	::1	TCP	8268	[TCP segment of a reassembled PDU]

/*! jQuery v1.7.1 jquery.com | jquery.org/license */
[...body follows]
```

With alacrity running on port 9001 (with branch https://github.com/yanns/alacrity/tree/buffer_body_when_incomplete):
```
wget http://localhost:9001/assets/javascripts/jquery-1.7.1.min.js
--2016-11-29 10:57:14--  http://localhost:9001/assets/javascripts/jquery-1.7.1.min.js
Resolving localhost... ::1, 127.0.0.1
Connecting to localhost|::1|:9001... failed: Connection refused.
Connecting to localhost|127.0.0.1|:9001... connected.
HTTP request sent, awaiting response...
```
```
3	0.000133	127.0.0.1	127.0.0.1	TCP	68	57435→9001 [SYN] Seq=0 Win=65535 Len=0 MSS=16344 WS=32 TSval=229077305 TSecr=0 SACK_PERM=1
4	0.000178	127.0.0.1	127.0.0.1	TCP	68	9001→57435 [SYN, ACK] Seq=0 Ack=1 Win=65535 Len=0 MSS=16344 WS=32 TSval=229077305 TSecr=229077305 SACK_PERM=1
5	0.000187	127.0.0.1	127.0.0.1	TCP	56	57435→9001 [ACK] Seq=1 Ack=1 Win=408288 Len=0 TSval=229077305 TSecr=229077305
6	0.000209	127.0.0.1	127.0.0.1	TCP	56	[TCP Window Update] 9001→57435 [ACK] Seq=1 Ack=1 Win=408288 Len=0 TSval=229077305 TSecr=229077305
7	0.000235	127.0.0.1	127.0.0.1	HTTP	236	GET /assets/javascripts/jquery-1.7.1.min.js HTTP/1.1 

GET /assets/javascripts/jquery-1.7.1.min.js HTTP/1.1
User-Agent: Wget/1.18 (darwin15.5.0)
Accept: */*
Accept-Encoding: identity
Host: localhost:9001
Connection: Keep-Alive

8	0.000264	127.0.0.1	127.0.0.1	TCP	56	9001→57435 [ACK] Seq=1 Ack=181 Win=408096 Len=0 TSval=229077305 TSecr=229077305
9	0.000880	127.0.0.1	127.0.0.1	TCP	68	57436→9000 [SYN] Seq=0 Win=65535 Len=0 MSS=16344 WS=32 TSval=229077305 TSecr=0 SACK_PERM=1
11	0.000923	127.0.0.1	127.0.0.1	TCP	56	57436→9000 [ACK] Seq=1 Ack=1 Win=408288 Len=0 TSval=229077305 TSecr=229077305
12	0.000930	127.0.0.1	127.0.0.1	TCP	56	[TCP Window Update] 9000→57436 [ACK] Seq=1 Ack=1 Win=408288 Len=0 TSval=229077305 TSecr=229077305
13	0.001382	127.0.0.1	127.0.0.1	HTTP	236	GET /assets/javascripts/jquery-1.7.1.min.js HTTP/1.1 

GET /assets/javascripts/jquery-1.7.1.min.js HTTP/1.1
User-Agent: Wget/1.18 (darwin15.5.0)
Accept: */*
Accept-Encoding: identity
Host: localhost:9001
Connection: Keep-Alive

14	0.001399	127.0.0.1	127.0.0.1	TCP	56	9000→57436 [ACK] Seq=1 Ack=181 Win=408096 Len=0 TSval=229077306 TSecr=229077306
15	0.006116	127.0.0.1	127.0.0.1	TCP	309	[TCP segment of a reassembled PDU]

HTTP/1.1 200 OK
ETag: "efab29516dc38c40118a01a7888ffd6b30e8b971"
Cache-Control: no-cache
Last-Modified: Tue, 08 Mar 2016 10:25:02 GMT
Content-Length: 93868
Content-Type: application/javascript; charset=utf-8
Date: Tue, 29 Nov 2016 10:10:04 GMT

16	0.006155	127.0.0.1	127.0.0.1	TCP	56	57436→9000 [ACK] Seq=181 Ack=254 Win=408032 Len=0 TSval=229077310 TSecr=229077310
17	0.008169	127.0.0.1	127.0.0.1	TCP	8248	[TCP segment of a reassembled PDU]

/*! jQuery v1.7.1 jquery.com | jquery.org/license */
[...body follows]


39	0.008518	127.0.0.1	127.0.0.1	HTTP	3812	HTTP/1.1 200 OK  (application/javascript)

[end of body]

40	0.008530	127.0.0.1	127.0.0.1	TCP	56	57436→9000 [ACK] Seq=181 Ack=94122 Win=314176 Len=0 TSval=229077312 TSecr=229077312
```

So we can see that alacrity is buffering the body as expected. The server sends the whole javascript.
But alacrity never sent the http response to the client.

### PR DESCRIPTION
**Pull request by hjr3**
Updated to use the new tokio-proto with Sink/Stream as the old crate had
some unhandled corner cases.

- Update code to conform to StreamingPipeline requirements
- Make sure of TcpClient abstraction
- Replace http parsing code with httparse crate
- Add large and streaming response body support

Fixes #35

### CODE REVIEW

**Comment by hjr3** [comment]
@yanns can you try the streaming response body on this one? it is working for me. i may spend another day cleaning up some code bits before merging.

**Comment by yanns** [comment]
This branch leads to a panic for me:

```
RUST_LOG=alacrity,tokio_core,tokio_proto cargo run --bin alacrity 127.0.0.1:9001 127.0.0.1:9000 127.0.0.1:9002
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/alacrity 127.0.0.1:9001 127.0.0.1:9000 127.0.0.1:9002`
DEBUG:tokio_core::reactor: adding a new I/O source
INFO:alacrity::proxy: Listening on: 127.0.0.1:9001
DEBUG:tokio_core::reactor: consuming notification queue
DEBUG:tokio_core::reactor: scheduling direction for: 0
DEBUG:tokio_core::reactor: loop poll - Duration { secs: 2, nanos: 191432796 }
DEBUG:tokio_core::reactor: loop time - Instant { t: 109610977194939 }
TRACE:tokio_core::reactor: event Ready {Readable} Token(2)
DEBUG:tokio_core::reactor: notifying a task handle
DEBUG:tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 113249 }
DEBUG:tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 121116 }
DEBUG:tokio_core::reactor: loop time - Instant { t: 109610977433637 }
TRACE:tokio_core::reactor: event Ready {Readable} Token(1)
DEBUG:tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 16956 }
DEBUG:tokio_core::reactor: consuming notification queue
DEBUG:tokio_core::reactor: adding a new I/O source
DEBUG:alacrity::proxy: Incoming connection on 127.0.0.1:51146
DEBUG:alacrity::pool::inner: Pool is cloaning (hehe) out 127.0.0.1:9000
DEBUG:alacrity::proxy: Preparing backend request to V4(127.0.0.1:9000)
DEBUG:tokio_core::reactor: adding a new I/O source
DEBUG:tokio_core::reactor: consuming notification queue
DEBUG:tokio_core::reactor: scheduling direction for: 0
DEBUG:tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 172660 }
DEBUG:tokio_core::reactor: loop time - Instant { t: 109610978050274 }
TRACE:tokio_core::reactor: event Ready {Readable | Writable} Token(4)
TRACE:tokio_core::reactor: event Ready {Writable} Token(6)
TRACE:tokio_core::reactor: event Ready {Readable} Token(5)
TRACE:tokio_core::reactor: event Ready {Readable} Token(3)
DEBUG:tokio_core::reactor: loop process - 4 events, Duration { secs: 0, nanos: 167349 }
DEBUG:tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 135547 }
DEBUG:tokio_core::reactor: loop time - Instant { t: 109610978359068 }
TRACE:tokio_core::reactor: event Ready {Readable} Token(9)
TRACE:tokio_proto::streaming::pipeline::advanced: Pipeline::tick
TRACE:alacrity::framed: flushing framed transport
TRACE:alacrity::framed: framed transport flushed
DEBUG:tokio_core::reactor: consuming notification queue
DEBUG:tokio_core::reactor: scheduling direction for: 1
TRACE:alacrity::framed: attempting to decode a frame
TRACE:alacrity::frontend: decode
DEBUG:alacrity::frontend: Raw request [71, 69, 84, 32, 47, 97, 115, 115, 101, 116, 115, 47, 106, 97, 118, 97, 115, 99, 114, 105, 112, 116, 115, 47, 106, 113, 117, 101, 114, 121, 45, 49, 46, 55, 46, 49, 46, 109, 105, 110, 46, 106, 115, 32, 72, 84, 84, 80, 47, 49, 46, 49, 13, 10, 85, 115, 101, 114, 45, 65, 103, 101, 110, 116, 58, 32, 87, 103, 101, 116, 47, 49, 46, 49, 56, 32, 40, 100, 97, 114, 119, 105, 110, 49, 53, 46, 53, 46, 48, 41, 13, 10, 65, 99, 99, 101, 112, 116, 58, 32, 42, 47, 42, 13, 10, 65, 99, 99, 101, 112, 116, 45, 69, 110, 99, 111, 100, 105, 110, 103, 58, 32, 105, 100, 101, 110, 116, 105, 116, 121, 13, 10, 72, 111, 115, 116, 58, 32, 108, 111, 99, 97, 108, 104, 111, 115, 116, 58, 57, 48, 48, 49, 13, 10, 67, 111, 110, 110, 101, 99, 116, 105, 111, 110, 58, 32, 75, 101, 101, 112, 45, 65, 108, 105, 118, 101, 13, 10, 13, 10]
TRACE:alacrity::framed: frame decoded from buffer
TRACE:tokio_proto::streaming::pipeline::advanced: process_out_frame
TRACE:tokio_proto::streaming::pipeline::advanced: read out message
TRACE:alacrity::proxy: frontend service
TRACE:alacrity::framed: attempting to decode a frame
TRACE:alacrity::frontend: decode
DEBUG:alacrity::frontend: Raw request []
DEBUG:alacrity::frontend: Partial request
DEBUG:tokio_core::reactor: consuming notification queue
DEBUG:tokio_core::reactor: scheduling direction for: 1
TRACE:tokio_proto::streaming::pipeline::advanced: write_in_frames
TRACE:alacrity::framed: flushing framed transport
TRACE:alacrity::framed: framed transport flushed
TRACE:tokio_proto::streaming::pipeline::advanced: write_in_body
DEBUG:tokio_proto::streaming::pipeline::advanced: write in body done
TRACE:alacrity::framed: flushing framed transport
TRACE:alacrity::framed: framed transport flushed
TRACE:tokio_core::reactor: event Ready {Readable} Token(7)
TRACE:tokio_proto::streaming::pipeline::advanced: Pipeline::tick
TRACE:alacrity::framed: flushing framed transport
TRACE:alacrity::framed: framed transport flushed
DEBUG:tokio_core::reactor: consuming notification queue
DEBUG:tokio_core::reactor: scheduling direction for: 2
TRACE:tokio_proto::streaming::pipeline::advanced: write_in_frames
TRACE:alacrity::framed: flushing framed transport
TRACE:alacrity::framed: framed transport flushed
TRACE:tokio_proto::streaming::pipeline::advanced: write_in_body
DEBUG:tokio_proto::streaming::pipeline::advanced: write in body done
TRACE:tokio_proto::streaming::pipeline::client: Dispatch::poll
TRACE:tokio_proto::streaming::pipeline::client:    --> received request
TRACE:tokio_proto::streaming::pipeline::advanced:    --> got message
TRACE:tokio_proto::streaming::pipeline::advanced: write_in_message
TRACE:tokio_proto::streaming::pipeline::advanced: got in_flight value without body
TRACE:alacrity::backend: encode
DEBUG:alacrity::backend: Request Message { message: <HTTP Request GET /assets/javascripts/jquery-1.7.1.min.js>, body: false }
TRACE:alacrity::framed: flushing framed transport
TRACE:alacrity::framed: writing; remaining=180
TRACE:alacrity::framed: framed transport flushed
TRACE:tokio_proto::streaming::pipeline::advanced: write_in_body
DEBUG:tokio_proto::streaming::pipeline::advanced: write in body done
TRACE:tokio_proto::streaming::pipeline::client: Dispatch::poll
TRACE:tokio_proto::streaming::pipeline::client:    --> not ready
TRACE:alacrity::framed: flushing framed transport
TRACE:alacrity::framed: framed transport flushed
DEBUG:tokio_core::reactor: loop process - 2 events, Duration { secs: 0, nanos: 546017 }
DEBUG:tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 133035 }
DEBUG:tokio_core::reactor: loop time - Instant { t: 109610979044577 }
TRACE:tokio_core::reactor: event Ready {Writable} Token(6)
DEBUG:tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 22942 }
DEBUG:tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 5177849 }
DEBUG:tokio_core::reactor: loop time - Instant { t: 109610984248774 }
TRACE:tokio_core::reactor: event Ready {Readable} Token(6)
DEBUG:tokio_core::reactor: notifying a task handle
DEBUG:tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 56318 }
DEBUG:tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 142170 }
DEBUG:tokio_core::reactor: loop time - Instant { t: 109610984451165 }
TRACE:tokio_core::reactor: event Ready {Readable} Token(7)
TRACE:tokio_proto::streaming::pipeline::advanced: Pipeline::tick
TRACE:alacrity::framed: flushing framed transport
TRACE:alacrity::framed: framed transport flushed
DEBUG:tokio_core::reactor: consuming notification queue
DEBUG:tokio_core::reactor: scheduling direction for: 2
TRACE:alacrity::framed: attempting to decode a frame
TRACE:alacrity::backend: decode
DEBUG:alacrity::response: Found content length of 93868
thread 'main' panicked at 'assertion failed: end <= self.buf.len()', /Users/yannsimon/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.1/src/io/frame.rs:67
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by hjr3** [comment]
What did you proxy? I will try and recreate.

**Comment by yanns** [comment]
This is a Scala application: https://github.com/yanns/play2-wiki-growth-sse.

I wanted to use it to test server send events, but for the moment, I'm just using for a very simple test:
```
wget http://localhost:9000/assets/javascripts/jquery-1.7.1.min.js
wget http://localhost:9001/assets/javascripts/jquery-1.7.1.min.js
```

**Comment by hjr3** [comment]
Great, I can recreate. I will fix in a bit!

**Comment by hjr3** [comment]
@yanns this update works with your play app

**Comment by yanns** [comment]
😍 😍 
Great work!

**Comment by hjr3** [comment]
I am working on making the body handling more robust. I will restore request body support during that time.

**Pull request merged**
